### ISSUE TITLE
Can I track red colors with a infrared sensor instead than a web camera?

### ISSUE THREAD

**Issue by programandoconro** [gaborvecsei/Color-Tracker#22]
Hi, I have an infrared array sensor connected to bus 0x68 in my raspberry pi. How can I track red colors from that input? The output is a console cam, code is available here: https://github.com/adafruit/Adafruit_CircuitPython_AMG88xx/blob/master/examples/amg88xx_rpi_thermal_cam_console.py

Thank you !!

**Comment by gaborvecsei** [comment]
Please see the provided examples: https://github.com/gaborvecsei/Color-Tracker/tree/master/examples
