### ISSUE TITLE
pip install color-tracker not working

### ISSUE THREAD

**Issue by danypepin1** [gaborvecsei/Color-Tracker#23]
Hi,

I wanted to try out your tools and i did pip install color-tracker

and i am getting this error : ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\users\\dany_\\appdata\\local\\programs\\python\\python39\\Lib\\site-packages\\cv2\\cv2.cp39-win_amd64.pyd'

any idea ?

Thanks a lot :)

**Comment by gaborvecsei** [comment]
The prolem is with your python setup/environment. This is an `OSError`.
