### ISSUE TITLE
color_tracker error

### ISSUE THREAD

**Issue by juanguren** [gaborvecsei/Color-Tracker#8]
Hello,

I´ve been trying to use this module, already installed it plus OpenCV but when I try to import the color_tracker:

`import cv2`
`import color_tracker`
`color_tracker.__version__
'0.1.0'`

There´s this error message:

> Traceback (most recent call last):
  File "D:/Proyectos_Python/Modulo_Color.py", line 2, in <module>
    import color_tracker
ImportError: No module named 'color_tracker'

I tried with `import tracker` but realized that is the `color_tracker` itself that´s needed. I would appreciate your help a lot.

PD: I leave a screenshot below:

![image](https://user-images.githubusercontent.com/34801285/39407991-e802ec7c-4b94-11e8-87cf-018d418d85ab.png)

**Comment by gaborvecsei** [comment]
Hi, Thanks for reaching out. I think the issue here is that you use a virtual environment but you installed the package at a different (maybe the default) location.

As I see you use PyChram. First you should check the `Project Interpreter`. If you can see the module `color_tracker there` then the issue is something else.

**Comment by juanguren** [comment]
Gábo, you were right. My location was different so I copied the package in it and it worked. It´s really amazing. Thank you!
PD: It recognizes my skin color, I ran the script for identifying a different one, but there´s something I don´t get. There´s this window for selecting HSV and so on.. 
But how can I select an exact color and save that parameter for the porgram?

**Comment by gaborvecsei** [comment]
Those are different things. The HSV color selector is only a "helper script" so you can experiment with the `colot_tracer` faster.

Basically you just run the HSV color selector and then, write down the numbers. I know, old-school... 😄  After that you just have to update the values in your program. This is how it works.

But if you have the right HSV colors in your mind, then you don't even need the color selector.

**Comment by juanguren** [comment]
Haha, makes sense now. 
After identifying the HSV, what´s the purpose of `upper` and `lower` values?
